{% set name = "xnemogcm" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xnemogcm-{{ version }}.tar.gz
  sha256: 68e9d91e756cf12d6aa07268ac4dc81fc64ef3cc1051be5dff54d0c9dc51392a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9
  run:
    - dask-core
    - netcdf4
    - python >=3.9
    - xarray

test:
  imports:
    - xnemogcm
  commands:
    - pip check
  requires:
    - pip
    - pre-commit

about:
  home: https://github.com/rcaneill/xnemogcm
  summary: Interface to open NEMO global circulation model output dataset and create a xgcm grid.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcaneill
