{% set name = "xnemogcm" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xnemogcm-{{ version }}.tar.gz
  sha256: 2e8686758ecb824592d13c702248325305d62b07f5f53680f054d7c617f59dc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dask-core
    - netcdf4
    - python >=3.8
    - xarray

test:
  imports:
    - xnemogcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rcaneill/xnemogcm
  summary: Interface to open NEMO global circulation model output dataset and create a xgcm grid.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcaneill
