{% set name = "xnemogcm" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xnemogcm-{{ version }}.tar.gz
  sha256: c4ed5a5839dcf50af1d9d7ead283be77354fc7b015d6d8658b8a6374301b2534

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - uv-build
    - python >=3.9
  run:
    - dask-core
    - netcdf4
    - python >=3.9
    - xarray

test:
  imports:
    - xnemogcm
  commands:
    - pip check
  requires:
    - pip
    - pre-commit

about:
  home: https://github.com/rcaneill/xnemogcm
  summary: Interface to open NEMO global circulation model output dataset and create a xgcm grid.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcaneill
