{% set name = "xnemogcm" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xnemogcm-{{ version }}.tar.gz
  sha256: 246dd1d2bcd1f9a4927d6a6e698701038605d1f633a59a750b67d0e03ec3b208

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - dask-core
    - netcdf4
    - python >={{ python_min }}
    - xarray

test:
  imports:
    - xnemogcm
  commands:
    - pip check
  requires:
    - pip
    - pre-commit
    - python {{ python_min }}

about:
  home: https://github.com/rcaneill/xnemogcm
  summary: Interface to open NEMO global circulation model output dataset and create a xgcm grid.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcaneill
